USE [master]
GO
/****** Object:  Database [EuroFinsToDo]    Script Date: 8/11/2019 8:21:34 PM ******/
CREATE DATABASE [EuroFinsToDo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EuroFinsToDo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\EuroFinsToDo.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'EuroFinsToDo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\EuroFinsToDo_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [EuroFinsToDo] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EuroFinsToDo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [EuroFinsToDo] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [EuroFinsToDo] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [EuroFinsToDo] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [EuroFinsToDo] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [EuroFinsToDo] SET ARITHABORT OFF 
GO
ALTER DATABASE [EuroFinsToDo] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [EuroFinsToDo] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [EuroFinsToDo] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [EuroFinsToDo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [EuroFinsToDo] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [EuroFinsToDo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [EuroFinsToDo] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [EuroFinsToDo] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [EuroFinsToDo] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [EuroFinsToDo] SET  DISABLE_BROKER 
GO
ALTER DATABASE [EuroFinsToDo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [EuroFinsToDo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [EuroFinsToDo] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [EuroFinsToDo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [EuroFinsToDo] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [EuroFinsToDo] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [EuroFinsToDo] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [EuroFinsToDo] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [EuroFinsToDo] SET  MULTI_USER 
GO
ALTER DATABASE [EuroFinsToDo] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [EuroFinsToDo] SET DB_CHAINING OFF 
GO
ALTER DATABASE [EuroFinsToDo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [EuroFinsToDo] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [EuroFinsToDo] SET DELAYED_DURABILITY = DISABLED 
GO
USE [EuroFinsToDo]
GO
/****** Object:  Table [dbo].[Log]    Script Date: 8/11/2019 8:21:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Log](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[UserId] [bigint] NULL,
	[RequestIpAddress] [varchar](50) NULL,
	[RequestUri] [varchar](500) NULL,
	[RequestMethod] [varchar](10) NULL,
	[RequestPostData] [nvarchar](max) NULL,
	[RequestTimestamp] [datetime] NULL,
	[ResponseStatusCode] [varchar](10) NULL,
	[ResponseReasonPhrase] [nvarchar](max) NULL,
	[ResponseErrorMessage] [nvarchar](max) NULL,
	[ResponseTimestamp] [datetime] NULL,
 CONSTRAINT [PK_Log] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 8/11/2019 8:21:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[UserName] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](max) NOT NULL,
	[Created_At] [datetime] NULL,
	[Updated_At] [datetime] NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserTasks]    Script Date: 8/11/2019 8:21:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserTasks](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[User_ID] [int] NOT NULL,
	[Title] [nvarchar](max) NOT NULL,
	[IsComplete] [bit] NOT NULL,
	[Created_At] [datetime] NULL,
	[Updated_At] [datetime] NULL,
 CONSTRAINT [PK_Tasks] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Users] ADD  CONSTRAINT [DF_Users_Created_At]  DEFAULT (getdate()) FOR [Created_At]
GO
ALTER TABLE [dbo].[Users] ADD  CONSTRAINT [DF_Users_Updated_At]  DEFAULT (getdate()) FOR [Updated_At]
GO
ALTER TABLE [dbo].[UserTasks] ADD  CONSTRAINT [DF_Tasks_IsComplete]  DEFAULT ((0)) FOR [IsComplete]
GO
ALTER TABLE [dbo].[UserTasks] ADD  CONSTRAINT [DF_Tasks_Created_At]  DEFAULT (getdate()) FOR [Created_At]
GO
ALTER TABLE [dbo].[UserTasks] ADD  CONSTRAINT [DF_Tasks_Updated_At]  DEFAULT (getdate()) FOR [Updated_At]
GO
ALTER TABLE [dbo].[UserTasks]  WITH CHECK ADD  CONSTRAINT [fk_b] FOREIGN KEY([User_ID])
REFERENCES [dbo].[Users] ([ID])
GO
ALTER TABLE [dbo].[UserTasks] CHECK CONSTRAINT [fk_b]
GO
USE [master]
GO
ALTER DATABASE [EuroFinsToDo] SET  READ_WRITE 
GO
